export enum CATEGORIES {
  SHONEN = 'Shonen',
  SHOUJO = 'Shoujo',
  SEINEN = 'Seinen',
  FANTASY = 'Fantasia',
  SCIENCE_FICTION = 'Ficção Científica',
  MECHA = 'Mecha',
  ROMANCE = 'Romance',
  DRAMA = 'Drama',
  COMEDY = 'Comédia',
  MYSTERY = 'Mistério',
  HORROR = 'Horror',
  SUPERHEROES = 'Super-heróis',
  ISEKAI = 'Isekai',
  SPORT = 'Esportes',
  ADVENTURE = 'Aventura',
  VAMPIRES = 'Vampiros',
  MAGIC = 'Magia',
  HISTORICAL = 'Histórico',
  MUSIC = 'Música',
  SLICE_OF_LIFE = 'Slice of Life',
  FANTASY_WORLD = 'Mundo Fantástico',
}
